name: test-pr-comment

on:
  issue_comment:
    types: [ created ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  set-path:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@deploy/codepush/') }}
    steps:
      - name: Search for path
        id: path
        # Extracts path from comment body i.e. @deploy/codepush/mobility => mobility 
        run: echo "path=$(echo "${{ github.event.comment.body }}" | sed -n 's/.*@deploy\/codepush\/\([^ \/]*\).*/\1/p')" >> "$GITHUB_OUTPUT"

      - name: Initialize repo
        uses: actions/checkout@v2

      # Checkout to branch of the pr using the gh cli and pull request URL
      - name: Checkout to pr branch
        run: gh pr checkout ${{ github.event.issue.pull_request.html_url }}

      - name: Get branch name
        id: commit-sha
        run: echo "commit-sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    outputs:
      path: ${{ steps.path.outputs.path }}
      commit-sha: ${{ steps.commit-sha.outputs.commit-sha }}

  do-some-actions:
    needs: set-path
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      commit-sha: ${{ needs.set-path.outputs.commit-sha }}
      throw-error: true
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    needs: do-some-actions
    if: always()
    steps:
      - name: Add rocket reaction
        uses: peter-evans/create-or-update-comment@v2
        if: success()
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
      
      - name: Add thumbs down reaction
        uses: peter-evans/create-or-update-comment@v2
        if: failure()
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: -1
  

    